#!/usr/bin/env node

import fs from 'fs/promises';
import path from 'path';
import { createInterface } from 'readline';

const envPath = path.join(process.cwd(), '.env');
const envExamplePath = path.join(process.cwd(), '.env.example');

/**
 * Create readline interface for user input
 */
function createReadline() {
  return createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

/**
 * Prompt user for input
 */
function prompt(question, defaultValue = '') {
  const rl = createReadline();
  
  return new Promise((resolve) => {
    const displayDefault = defaultValue ? ` [${defaultValue}]` : '';
    rl.question(`${question}${displayDefault}: `, (answer) => {
      rl.close();
      resolve(answer.trim() || defaultValue);
    });
  });
}

/**
 * Load existing .env file
 */
async function loadExistingEnv() {
  try {
    const content = await fs.readFile(envPath, 'utf-8');
    const env = {};
    
    content.split('\n').forEach(line => {
      const trimmed = line.trim();
      if (trimmed && !trimmed.startsWith('#')) {
        const [key, ...valueParts] = trimmed.split('=');
        if (key) {
          env[key.trim()] = valueParts.join('=').trim();
        }
      }
    });
    
    return env;
  } catch (error) {
    if (error.code === 'ENOENT') {
      return {};
    }
    throw error;
  }
}

/**
 * Save configuration to .env file
 */
async function saveEnv(config) {
  const lines = [
    '# Botline Configuration',
    '# Generated by setup script',
    '',
    '# Server Configuration',
    `PORT=${config.PORT}`,
    `NODE_ENV=${config.NODE_ENV}`,
    '',
    '# Security Configuration',
    `ALLOWED_IPS=${config.ALLOWED_IPS}`,
    `SHARED_SECRET=${config.SHARED_SECRET}`,
    `ALLOWED_USERS=${config.ALLOWED_USERS}`,
    '',
    '# Slack Configuration',
    `SLACK_BOT_TOKEN=${config.SLACK_BOT_TOKEN}`,
    `SLACK_APP_TOKEN=${config.SLACK_APP_TOKEN}`,
    `SLACK_SIGNING_SECRET=${config.SLACK_SIGNING_SECRET}`,
    '',
    '# Telegram Configuration',
    `TELEGRAM_BOT_TOKEN=${config.TELEGRAM_BOT_TOKEN}`,
    `TELEGRAM_WEBHOOK_URL=${config.TELEGRAM_WEBHOOK_URL}`,
    '',
    '# AI Agent Configuration',
    '# Claude',
    `CLAUDE_API_KEY=${config.CLAUDE_API_KEY}`,
    `CLAUDE_MODEL=${config.CLAUDE_MODEL}`,
    '',
    '# OpenRouter',
    `OPENROUTER_API_KEY=${config.OPENROUTER_API_KEY}`,
    `OPENROUTER_MODEL=${config.OPENROUTER_MODEL}`,
    '',
    '# Default AI Agent',
    `DEFAULT_AGENT=${config.DEFAULT_AGENT}`,
    '',
    '# Logging',
    `LOG_LEVEL=${config.LOG_LEVEL}`,
  ];
  
  await fs.writeFile(envPath, lines.join('\n'));
}

/**
 * Main setup function
 */
async function setup() {
  console.log('\n🤖 Botline Setup\n');
  console.log('This will guide you through configuring Botline.');
  console.log('Press Enter to keep existing values or skip optional fields.\n');

  // Check for --reset flag
  const shouldReset = process.argv.includes('--reset');
  
  let existingConfig = {};
  if (!shouldReset) {
    existingConfig = await loadExistingEnv();
    if (Object.keys(existingConfig).length > 0) {
      console.log('📝 Found existing configuration. Press Enter to keep current values.\n');
    }
  } else {
    console.log('🔄 Reset flag detected. Starting fresh configuration.\n');
  }

  const config = {};

  // Server Configuration
  console.log('=== Server Configuration ===');
  config.PORT = await prompt('Server port', existingConfig.PORT || '3000');
  config.NODE_ENV = await prompt('Environment (development/production)', existingConfig.NODE_ENV || 'development');

  // Security Configuration
  console.log('\n=== Security Configuration ===');
  config.ALLOWED_IPS = await prompt('Allowed IPs (comma-separated)', existingConfig.ALLOWED_IPS || '127.0.0.1,::1');
  config.SHARED_SECRET = await prompt('Shared secret (optional)', existingConfig.SHARED_SECRET || '');
  config.ALLOWED_USERS = await prompt('Allowed users (comma-separated, optional)', existingConfig.ALLOWED_USERS || '');

  // Slack Configuration
  console.log('\n=== Slack Configuration ===');
  const configureSlack = await prompt('Configure Slack? (y/n)', existingConfig.SLACK_BOT_TOKEN ? 'y' : 'n');
  
  if (configureSlack.toLowerCase() === 'y') {
    config.SLACK_BOT_TOKEN = await prompt('Slack Bot Token (xoxb-...)', existingConfig.SLACK_BOT_TOKEN || '');
    config.SLACK_APP_TOKEN = await prompt('Slack App Token (xapp-...)', existingConfig.SLACK_APP_TOKEN || '');
    config.SLACK_SIGNING_SECRET = await prompt('Slack Signing Secret', existingConfig.SLACK_SIGNING_SECRET || '');
  } else {
    config.SLACK_BOT_TOKEN = '';
    config.SLACK_APP_TOKEN = '';
    config.SLACK_SIGNING_SECRET = '';
  }

  // Telegram Configuration
  console.log('\n=== Telegram Configuration ===');
  const configureTelegram = await prompt('Configure Telegram? (y/n)', existingConfig.TELEGRAM_BOT_TOKEN ? 'y' : 'n');
  
  if (configureTelegram.toLowerCase() === 'y') {
    config.TELEGRAM_BOT_TOKEN = await prompt('Telegram Bot Token', existingConfig.TELEGRAM_BOT_TOKEN || '');
    config.TELEGRAM_WEBHOOK_URL = await prompt('Telegram Webhook URL (optional)', existingConfig.TELEGRAM_WEBHOOK_URL || '');
  } else {
    config.TELEGRAM_BOT_TOKEN = '';
    config.TELEGRAM_WEBHOOK_URL = '';
  }

  // AI Agent Configuration
  console.log('\n=== AI Agent Configuration ===');
  const configureClaude = await prompt('Configure Claude? (y/n)', existingConfig.CLAUDE_API_KEY ? 'y' : 'n');
  
  if (configureClaude.toLowerCase() === 'y') {
    config.CLAUDE_API_KEY = await prompt('Claude API Key', existingConfig.CLAUDE_API_KEY || '');
    config.CLAUDE_MODEL = await prompt('Claude Model', existingConfig.CLAUDE_MODEL || 'claude-3-5-sonnet-20241022');
  } else {
    config.CLAUDE_API_KEY = '';
    config.CLAUDE_MODEL = 'claude-3-5-sonnet-20241022';
  }

  const configureOpenRouter = await prompt('Configure OpenRouter? (y/n)', existingConfig.OPENROUTER_API_KEY ? 'y' : 'n');
  
  if (configureOpenRouter.toLowerCase() === 'y') {
    config.OPENROUTER_API_KEY = await prompt('OpenRouter API Key', existingConfig.OPENROUTER_API_KEY || '');
    config.OPENROUTER_MODEL = await prompt('OpenRouter Model', existingConfig.OPENROUTER_MODEL || 'anthropic/claude-3.5-sonnet');
  } else {
    config.OPENROUTER_API_KEY = '';
    config.OPENROUTER_MODEL = 'anthropic/claude-3.5-sonnet';
  }

  // Default Agent
  let defaultAgent = 'claude';
  if (config.CLAUDE_API_KEY && !config.OPENROUTER_API_KEY) {
    defaultAgent = 'claude';
  } else if (config.OPENROUTER_API_KEY && !config.CLAUDE_API_KEY) {
    defaultAgent = 'openrouter';
  } else if (config.CLAUDE_API_KEY && config.OPENROUTER_API_KEY) {
    defaultAgent = await prompt('Default AI Agent (claude/openrouter)', existingConfig.DEFAULT_AGENT || 'claude');
  }
  config.DEFAULT_AGENT = defaultAgent;

  // Logging
  console.log('\n=== Logging Configuration ===');
  config.LOG_LEVEL = await prompt('Log Level (error/warn/info/debug)', existingConfig.LOG_LEVEL || 'info');

  // Save configuration
  console.log('\n💾 Saving configuration...');
  await saveEnv(config);
  
  console.log('✅ Configuration saved to .env');
  console.log('\n🚀 You can now start Botline with: npm start');
  console.log('\nℹ️  To reset configuration, run: npm run setup -- --reset\n');
}

// Run setup
setup().catch(error => {
  console.error('❌ Setup failed:', error);
  process.exit(1);
});
